# Generated by Django 2.2.10 on 2020-04-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0002_posttwo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostTwo',
        ),
    ]
